server.port= 8080

spring.application.name=jobportal
spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud_name=dyucgevvq
cloudinary.api_key=983964335226331
cloudinary.api_secret=9m1DUzGJtMU0BnUVwjim2mTrphU

jwt.secret=MySuperSecretKeyForJwtSigningMustBeLongEnough12345
jwt.expiration=86400000

# Stripe Configuration
stripe.secretKey=sk_test_51SPLNiQWlUGrlx1XQy7u3m0hkPcfIodJCaRZ99eoSwtgkr3oUwJkwnLc4UNWosZ3pBGpAp3iyMvjsmhtypkbdarC000DtanLzF
stripe.publishableKey=pk_test_51SPLNiQWlUGrlx1XM4aLdo5JxpHmP9EBmsUKm7SrqNGzIYUWsBZcoTWpuUedJAHoKdcK6mZZwn8yW7z6FipyLMHV00geGkkKWi

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
