spring.application.name=jobportal
spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud_name=dyucgevvq
cloudinary.api_key=983964335226331
cloudinary.api_secret=9m1DUzGJtMU0BnUVwjim2mTrphU

jwt.secret=MySuperSecretKeyForJwtSigningMustBeLongEnough12345
jwt.expiration=86400000

# Stripe Configuration
stripe.secretKey=sk_test_51T3ooZBCxJ6bJuRfAd0J0e4iClbOvjKRIIFSPCeRvj7QhGnCW7rcaxey2KCSB1T0ZRI96Zpz3AufqxOYSQAfEkwA00uIgoBrAF
stripe.publishableKey=pk_test_51T3ooZBCxJ6bJuRfRCKzKtzud01Jlc0QJiZjhuDNY5qwXDjnYBbIjWwA5X3X99GusQ82Kpf173Oy3rFw2eAgpHbl00NRIO8Jqv

